### ISSUE TITLE
Support Wikiwand

### ISSUE THREAD

**Issue by johan456789** [vinc96/Wikitube#2]
It only takes 2 else ifs to support wikiwand:
```js
// in first_load
else if ($('#fullContent').length) { // wikiwand
      container.insertBefore('#fullContent');
    }
```
```js
// in main code
 else if ($('#fullContent').length) // wikiwand
    {
      title_text = $('.firstHeading > span').text();
      num_videos_to_load = Math.floor($('#article_content_wrapper').width() / 350); //video width = 350px
    }
```

I have working code [here](https://gist.github.com/johan456789/1dca81160d43881b853279cbe2eac061).

I'm thinking sending a pull request after you fixed #1, or if you don't mind the commit history is different from Greasy Fork, I can directly send a pull request with support of Wikiwand and bump the version to 3.4.

**Comment by yiminzme** [comment]
Hi Johan, please directly send a pull request with the support of Wikiwand and bump the version to 3.4.
Thanks a lot!
